# Inspecting DataFrames Using head(), info(), and describe()

## Learning Objectives
- Use `head()` to preview DataFrame contents
- Use `info()` to understand structure and data types
- Use `describe()` to summarize numeric data
- Detect obvious data issues early
- Inspect data confidently before processing

---

## Why Inspection Matters

**Inspection is the most important step after loading data.**

Common mistakes avoided by proper inspection:
- Starting analysis without understanding the data
- Misinterpreting column data types
- Missing hidden null values
- Drawing conclusions from incomplete information

**Think of inspection as reading the dataset before using it.**

In [1]:
# Import necessary libraries
import pandas as pd
import numpy as np

## Step 1: Load the Dataset

We'll use the employee survey data for demonstration.

In [2]:
# Load the employee survey data from raw file
df = pd.read_csv('../data/raw/employee_survey_2026_Q1.csv')

print("✓ Data loaded successfully!")
print(f"Dataset shape: {df.shape}")
print(f"Total rows: {df.shape[0]}, Total columns: {df.shape[1]}")

✓ Data loaded successfully!
Dataset shape: (30, 9)
Total rows: 30, Total columns: 9

In [3]:
# Let's explore the shape in detail
print("=" * 80)
print("SHAPE BREAKDOWN")
print("=" * 80)

shape_tuple = df.shape
print(f"Full shape tuple: {shape_tuple}")
print(f"Type: {type(shape_tuple)}")

# Access individual elements
num_rows = df.shape[0]
num_cols = df.shape[1]

print(f"\nNumber of ROWS (observations): {num_rows:,}")
print(f"Number of COLUMNS (features): {num_cols}")

# Understand what each represents
print("\n📍 What rows represent:")
print(f"   Each of the {num_rows:,} rows is ONE employee survey response")

print("\n📍 What columns represent:")
print(f"   Each of the {num_cols} columns is ONE attribute or measurement")
print(f"   Total data elements: {num_rows * num_cols:,}")

# Alternative methods to get rows/columns
print("\n✓ Alternative ways to get this information:")
print(f"   len(df) = {len(df)} (number of rows)")
print(f"   len(df.columns) = {len(df.columns)} (number of columns)")
print(f"   df.index.size = {df.index.size} (number of rows)")

================================================================================
SHAPE BREAKDOWN
================================================================================
Full shape tuple: (30, 9)
Type: <class 'tuple'>

Number of ROWS (observations): 30
Number of COLUMNS (features): 9

📍 What rows represent:
   Each of the 30 rows is ONE employee survey response

📍 What columns represent:
   Each of the 9 columns is ONE attribute or measurement
   Total data elements: 270

✓ Alternative ways to get this information:
   len(df) = 30 (number of rows)
   len(df.columns) = 9 (number of columns)
   df.index.size = 30 (number of rows)

---

## Understanding DataFrame Shape

### What Is Shape?

The `shape` attribute returns a **tuple** with (rows, columns).

**Shape tells you:**
- How many observations (records) you have
- How many variables (features) you have
- The overall size of your dataset

**Example:** A shape of (100, 5) means:
- 100 rows (observations/records)
- 5 columns (features/variables)

---

## 1. Inspecting Data with head()

### Purpose: Quick Visual Preview

The `head()` method shows the **first few rows** of your DataFrame.

**What you can learn from head():**
- Column names
- Sample values for each column
- Data alignment and formatting
- General structure at a glance

**Default behavior:** Shows the first 5 rows

In [4]:
# Display the first 5 rows (default)
print("=" * 80)
print("PREVIEW: First 5 rows using head()")
print("=" * 80)

df.head()

================================================================================
PREVIEW: First 5 rows using head()
================================================================================

,employee_id,department,survey_date,satisfaction_score,work_life_balance,management_support,career_growth,team_collaboration,response_text
0,1001,Engineering,2026-01-15,7,8,6,5,9,Great team environment but limited growth oppo...
1,1002,Marketing,2026-01-16,9,9,8,7,8,Very satisfied with work-life balance and supp...
2,1003,Sales,2026-01-17,4,3,4,3,5,High pressure environment with poor work-life ...
3,1004,Engineering,2026-01-18,8,7,8,7,9,Good technical challenges and collaborative team
4,1005,HR,2026-01-19,6,7,5,4,6,Decent work environment but lack career advanc...

In [ ]:
# You can specify a different number of rows
print("=" * 80)
print("PREVIEW: First 10 rows using head(10)")
print("=" * 80)

df.head(10)

In [ ]:
# Also useful: tail() shows the LAST few rows
print("=" * 80)
print("PREVIEW: Last 5 rows using tail()")
print("=" * 80)

df.tail()

### What Did We Learn from head()?

From the preview above, we can observe:
- **Column names**: employee_id, department, survey_date, satisfaction_score, etc.
- **Data types (visual guess)**: 
  - employee_id appears to be numeric
  - department appears to be text/categorical
  - satisfaction_score appears to be numeric
  - response_text contains free-form text
- **Sample values**: We can see actual employee survey responses
- **No obvious formatting issues** in the first few rows

**Key Point:** head() gives you a quick visual check, but it doesn't tell you about data types, missing values, or overall structure. That's where info() comes in!

---

## 2. Inspecting Structure with info()

### Purpose: Understand DataFrame Structure and Health

The `info()` method provides a **comprehensive structural summary**.

**What you can learn from info():**
- Total number of rows and columns
- Column names
- **Data types** for each column (int64, float64, object, etc.)
- **Non-null counts** (reveals missing values)
- Memory usage

**This is the most important inspection method for understanding data structure.**

In [7]:
# Get detailed structural information
print("=" * 80)
print("STRUCTURE: DataFrame Info")
print("=" * 80)

df.info()

================================================================================
STRUCTURE: DataFrame Info
================================================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   employee_id         30 non-null     int64
 1   department          30 non-null     object
 2   survey_date         30 non-null     object
 3   satisfaction_score  30 non-null     int64
 4   work_life_balance   30 non-null     int64
 5   management_support  30 non-null     int64
 6   career_growth       30 non-null     int64
 7   team_collaboration  30 non-null     int64
 8   response_text       30 non-null     object
dtypes: int64(6), object(3)
memory usage: 2.2+ KB

In [5]:
# Detailed data type inspection
print("=" * 80)
print("COLUMN DATA TYPES - DETAILED INSPECTION")
print("=" * 80)

# Get data types
print("\n1️⃣ Data Types by Column:")
print(df.dtypes)

# Count each data type
print("\n2️⃣ Data Type Summary:")
print(df.dtypes.value_counts())

# Get more info per column
print("\n3️⃣ Detailed Column Information:")
for column in df.columns:
    dtype = df[column].dtype
    unique_count = df[column].nunique()
    null_count = df[column].isnull().sum()
    print(f"   {column}:")
    print(f"      Type: {dtype}")
    print(f"      Unique values: {unique_count}")
    print(f"      Missing values: {null_count}")
    if dtype == 'object':
        sample_values = df[column].unique()[:3]
        print(f"      Sample values: {sample_values}")
    print()

================================================================================
COLUMN DATA TYPES - DETAILED INSPECTION
================================================================================

1️⃣ Data Types by Column:
employee_id            int64
department            object
survey_date           object
satisfaction_score     int64
work_life_balance      int64
management_support     int64
career_growth          int64
team_collaboration     int64
response_text         object
dtype: object

2️⃣ Data Type Summary:
int64     6
object    3
Name: count, dtype: int64

3️⃣ Detailed Column Information:
   employee_id:
      Type: int64
      Unique values: 30
      Missing values: 0

   department:
      Type: object
      Unique values: 6
      Missing values: 0
      Sample values: ['Engineering' 'Marketing' 'Sales']

   survey_date:
      Type: object
      Unique values: 30
      Missing values: 0
      Sample values: ['2026-01-15' '2026-01-16' '2026-01-17']

   satisfaction_score:
      Type: int64
      Unique values: 9
      Missing values: 0

   work_life_balance:
      Type: int64
      Unique values: 10
      Missing values: 0

   management_support:
      Type: int64
      Unique values: 8
      Missing values: 0

   career_growth:
      Type: int64
      Unique values: 9
      Missing values: 0

   team_collaboration:
      Type: int64
      Unique values: 8
      Missing values: 0

   response_text:
      Type: object
      Unique values: 30
      Missing values: 0
      Sample values: ['Great team environment but limited growth opportunities'
 'Very satisfied with work-life balance and supportive management'
 'High pressure environment with poor work-life balance']

In [6]:
# Detect type-related issues
print("=" * 80)
print("DETECTING TYPE-RELATED ISSUES")
print("=" * 80)

# Issue 1: Check for numeric columns stored as object
print("\n🔍 Issue 1: Numeric Data Stored as Text?")
for col in df.columns:
    if df[col].dtype == 'object':
        # Try to convert to numeric and see if it works
        try:
            numeric_test = pd.to_numeric(df[col], errors='coerce')
            non_null_original = df[col].notna().sum()
            non_null_converted = numeric_test.notna().sum()
            
            if non_null_converted > 0:
                print(f"   ⚠️  '{col}' is 'object' but contains numeric values!")
                print(f"      Could convert {non_null_converted} values to numeric")
        except:
            pass

# Issue 2: Check for date-like columns
print("\n🔍 Issue 2: Dates Stored as Text?")
for col in df.columns:
    if df[col].dtype == 'object':
        # Check if column name suggests it's a date
        if 'date' in col.lower() or 'time' in col.lower():
            print(f"   ⚠️  '{col}' has 'date' in name but dtype is 'object'")
            sample = df[col].iloc[0]
            print(f"      Sample value: {sample}")
            print(f"      Should probably be datetime64")

# Issue 3: Check for columns with unexpected missing values
print("\n🔍 Issue 3: Missing Values That Affect Type?")
for col in df.columns:
    if df[col].dtype == 'float64':
        # Check if it's truly float or if it's int with NaN
        if df[col].notna().all() or df[col].dropna().equals(df[col].dropna().astype('int64').astype('float64')):
            missing = df[col].isnull().sum()
            if missing == 0:
                print(f"   ✓ '{col}' is float64 with no missing values")

# Issue 4: Check value ranges
print("\n🔍 Issue 4: Invalid or Suspicious Values?")
print(f"   satisfaction_score range: {df['satisfaction_score'].min()} to {df['satisfaction_score'].max()}")
print(f"   work_life_balance range: {df['work_life_balance'].min()} to {df['work_life_balance'].max()}")
print(f"   management_support range: {df['management_support'].min()} to {df['management_support'].max()}")

================================================================================
DETECTING TYPE-RELATED ISSUES
================================================================================

🔍 Issue 1: Numeric Data Stored as Text?

🔍 Issue 2: Dates Stored as Text?
   ⚠️  'survey_date' has 'date' in name but dtype is 'object'
      Sample value: 2026-01-15
      Should probably be datetime64

🔍 Issue 3: Missing Values That Affect Type?

🔍 Issue 4: Invalid or Suspicious Values?
   satisfaction_score range: 2 to 10
   work_life_balance range: 1 to 10
   management_support range: 2 to 9

---

## Detecting Type-Related Issues

### Red Flags to Watch For

**1. Numeric Data Stored as Object (Text)**
```
❌ Problem: salary column stored as 'object' (text) when it should be numeric
✓ Solution: Convert with pd.to_numeric()
```

**2. Dates Stored as Text**
```
❌ Problem: survey_date column is 'object' instead of 'datetime64'
✓ Solution: Convert with pd.to_datetime()
```

**3. Missing Values Affecting Type Detection**
```
❌ Problem: Column with mostly numbers but one NaN becomes 'float64'
✓ Solution: Check for and handle missing values
```

**4. Mixed Types in Same Column**
```
❌ Problem: Column contains both numbers and text
✓ Solution: Investigate and separate or standardize
```

### How to Detect These Issues

Let me demonstrate detection techniques:

---

## Understanding Column Data Types - Deep Dive

### Why Data Types Matter

**Data types control what operations are valid.**

Common Pandas data types:
- `int64` → Integers (whole numbers)
- `float64` → Decimals (numbers with decimal points)
- `object` → Text, strings, or mixed types
- `datetime64` → Dates and times
- `bool` → True/False values
- `category` → Categorical data (limited distinct values)

### Impact of Wrong Data Types

**Scenario 1: Numeric stored as text (object)**
```python
# Wrong: This is text "100", not number 100
salary = "100"
result = salary + 50  # ERROR! Can't add number to text
```

**Scenario 2: Date stored as text**
```python
# Wrong: Date as text can't calculate days between dates
date = "2026-01-15"
future = date + pd.Timedelta(days=5)  # ERROR! Can't add to text
```

**Scenario 3: Categorical stored as object**
```python
# Inefficient: Using text for limited values wastes memory
department = "Engineering"  # Should be category
# With many repeated values, category is much more efficient
```

### Understanding the info() Output

Let's break down what info() tells us:

1. **RangeIndex**: The index (row labels) - shows how many rows exist
2. **Data columns**: Total number of columns
3. **Column details**:
   - **Column name**
   - **Non-Null Count**: How many values are NOT missing
   - **Dtype**: Data type (int64, float64, object, datetime64, etc.)

4. **dtypes summary**: Quick count of each data type
5. **Memory usage**: How much RAM the DataFrame uses

### Critical Insights:

**If Non-Null Count < Total Rows** → Missing values exist in that column!

**Data type matters:**
- `int64` → Integer numbers (1, 2, 3)
- `float64` → Decimal numbers (1.5, 2.7)
- `object` → Text/strings or mixed types
- `datetime64` → Dates and times

**Common issues detected by info():**
- Numeric columns stored as 'object' (needs conversion)
- Date columns not recognized as datetime
- Missing values in critical columns

In [8]:
# Let's check for missing values explicitly
print("=" * 80)
print("MISSING VALUES: Count per Column")
print("=" * 80)

missing_counts = df.isnull().sum()
print(missing_counts)

print("\n" + "=" * 80)
print("MISSING VALUES: Percentage per Column")
print("=" * 80)

missing_percent = (df.isnull().sum() / len(df)) * 100
print(missing_percent.round(2))

================================================================================
MISSING VALUES: Count per Column
================================================================================
employee_id           0
department            0
survey_date           0
satisfaction_score    0
work_life_balance     0
management_support    0
career_growth         0
team_collaboration    0
response_text         0
dtype: int64

================================================================================
MISSING VALUES: Percentage per Column
================================================================================
employee_id           0.0
department            0.0
survey_date           0.0
satisfaction_score    0.0
work_life_balance     0.0
management_support    0.0
career_growth         0.0
team_collaboration    0.0
response_text         0.0
dtype: float64

---

## 3. Summarizing Data with describe()

### Purpose: Statistical Summary of Numeric Columns

The `describe()` method provides **statistical summaries** for numeric data.

**What you can learn from describe():**
- Count of non-null values
- Mean (average)
- Standard deviation (spread)
- Minimum value
- 25th percentile (Q1)
- 50th percentile (median)
- 75th percentile (Q3)
- Maximum value

**Default behavior:** Only shows numeric columns

In [9]:
# Get statistical summary of numeric columns
print("=" * 80)
print("STATISTICS: Numeric Column Summary")
print("=" * 80)

df.describe()

================================================================================
STATISTICS: Numeric Column Summary
================================================================================

,employee_id,satisfaction_score,work_life_balance,management_support,career_growth,team_collaboration
count,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000
mean,1015.500000,6.466667,6.300000,5.966667,5.333333,6.833333
std,8.803408,1.960530,2.246069,1.865907,1.917853,1.966676
min,1001.000000,2.000000,1.000000,2.000000,1.000000,3.000000
25%,1008.250000,5.000000,5.000000,5.000000,4.000000,5.250000
50%,1015.500000,6.500000,7.000000,6.000000,5.000000,7.000000
75%,1022.750000,8.000000,8.000000,7.750000,7.000000,8.000000
max,1030.000000,10.000000,10.000000,9.000000,9.000000,10.000000

### Understanding the describe() Output

**What each row means:**

1. **count**: Number of non-missing values
   - If count < total rows → missing values exist

2. **mean**: Average value
   - Sensitive to outliers

3. **std**: Standard deviation (how spread out the data is)
   - High std = high variability
   - Low std = values close to the mean

4. **min**: Smallest value
   - Check for unrealistic values (e.g., negative ages)

5. **25% (Q1)**: First quartile - 25% of values are below this

6. **50% (median)**: Middle value when data is sorted
   - Not affected by outliers like mean is

7. **75% (Q3)**: Third quartile - 75% of values are below this

8. **max**: Largest value
   - Check for unrealistic values or outliers

### What to Look For:

**Potential outliers:**
- If max is much larger than 75% → possible high outlier
- If min is much smaller than 25% → possible low outlier

**Data range:**
- Check if min/max make sense for the variable
- Example: Satisfaction scores should be within expected range (e.g., 1-10)

**Distribution shape:**
- If mean ≈ median → roughly symmetric distribution
- If mean > median → right-skewed (pulled by high values)
- If mean < median → left-skewed (pulled by low values)

In [ ]:
# You can also describe categorical columns using include='object'
print("=" * 80)
print("STATISTICS: Categorical Column Summary")
print("=" * 80)

df.describe(include='object')

### Understanding describe() for Categorical Data

For object/categorical columns, describe() shows:

1. **count**: Number of non-missing values
2. **unique**: Number of unique/distinct values
3. **top**: Most frequently occurring value
4. **freq**: How many times the top value appears

**This is useful for:**
- Understanding category distributions
- Identifying highly imbalanced categories
- Detecting unexpected values

In [ ]:
# Get summary for ALL columns (numeric and categorical)
print("=" * 80)
print("STATISTICS: All Columns Summary")
print("=" * 80)

df.describe(include='all')

---

## 4. Knowing When to Use Each Method

### Building Inspection Intuition

Each inspection method answers a different question:

| Method | Question It Answers | When to Use |
|--------|-------------------|-------------|
| **head()** | "What does the data look like?" | Quick visual preview, check formatting |
| **info()** | "How is the data structured?" | Check data types, find missing values |
| **describe()** | "What are the numeric patterns?" | Understand distributions, spot outliers |

### Recommended Inspection Workflow:

```python
# Step 1: Load data
df = pd.read_csv('data.csv')

# Step 2: Check shape
print(df.shape)

# Step 3: Preview data
df.head()

# Step 4: Check structure and types
df.info()

# Step 5: Get statistical summary
df.describe()
```

**Always inspect BEFORE cleaning, analysis, or modeling!**

---

## Complete Inspection Example

Let's demonstrate a complete inspection workflow:

In [10]:
# COMPLETE INSPECTION WORKFLOW

def inspect_dataframe(df, name="DataFrame"):
    """
    Comprehensive DataFrame inspection function.
    
    Parameters:
    -----------
    df : pandas.DataFrame
        The DataFrame to inspect
    name : str
        Name to display in the report
    """
    print("\n" + "=" * 80)
    print(f"INSPECTION REPORT: {name}")
    print("=" * 80)
    
    # 1. Shape
    print(f"\n📊 SHAPE")
    print(f"   Rows: {df.shape[0]:,}")
    print(f"   Columns: {df.shape[1]}")
    
    # 2. Preview
    print(f"\n👀 PREVIEW (First 3 rows)")
    print(df.head(3))
    
    # 3. Structure
    print(f"\n🏗️  STRUCTURE")
    df.info()
    
    # 4. Missing Values
    print(f"\n❓ MISSING VALUES")
    missing = df.isnull().sum()
    missing_percent = (missing / len(df)) * 100
    missing_df = pd.DataFrame({
        'Missing Count': missing,
        'Percentage': missing_percent.round(2)
    })
    if missing.sum() == 0:
        print("   ✓ No missing values detected!")
    else:
        print(missing_df[missing_df['Missing Count'] > 0])
    
    # 5. Numeric Summary
    print(f"\n📈 NUMERIC SUMMARY")
    print(df.describe())
    
    # 6. Categorical Summary
    categorical_cols = df.select_dtypes(include='object').columns
    if len(categorical_cols) > 0:
        print(f"\n📝 CATEGORICAL SUMMARY")
        print(df.describe(include='object'))
    
    print("\n" + "=" * 80)
    print("✓ Inspection Complete")
    print("=" * 80)

# Run the inspection
inspect_dataframe(df, "Employee Survey Q1 2026")

================================================================================
INSPECTION REPORT: Employee Survey Q1 2026
================================================================================

📊 SHAPE
   Rows: 30
   Columns: 9

👀 PREVIEW (First 3 rows)
   employee_id   department survey_date  satisfaction_score  \
0         1001  Engineering  2026-01-15                   7
1         1002    Marketing  2026-01-16                   9
2         1003        Sales  2026-01-17                   4

   work_life_balance  management_support  career_growth  team_collaboration  \
0                  8                   6              5                   9
1                  9                   8              7                   8
2                  3                   4              3                   5

                                       response_text
0  Great team environment but limited growth oppo...
1  Very satisfied with work-life balance and supp...
2  High pressure environment with poor work-life ...

🏗️  STRUCTURE
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   employee_id         30 non-null     int64
 1   department          30 non-null     object
 2   survey_date         30 non-null     object
 3   satisfaction_score  30 non-null     int64
 4   work_life_balance   30 non-null     int64
 5   management_support  30 non-null     int64
 6   career_growth       30 non-null     int64
 7   team_collaboration  30 non-null     int64
 8   response_text       30 non-null     object
dtypes: int64(6), object(3)
memory usage: 2.2+ KB

❓ MISSING VALUES
   ✓ No missing values detected!

📈 NUMERIC SUMMARY
       employee_id  satisfaction_score  work_life_balance  management_support  \
count    30.000000           30.000000          30.000000           30.000000
mean   1015.500000            6.466667           6.300000            5.966667
std       8.803408            1.960530           2.246069            1.865907
min    1001.000000            2.000000           1.000000            2.000000
25%    1008.250000            5.000000           5.000000            5.000000
50%    1015.500000            6.500000           7.000000            6.000000
75%    1022.750000            8.000000           8.000000            7.750000
max    1030.000000           10.000000          10.000000            9.000000

       career_growth  team_collaboration
count      30.000000           30.000000
mean        5.333333            6.833333
std         1.917853            1.966676
min         1.000000            3.000000
25%         4.000000            5.250000
50%         5.000000            7.000000
75%         7.000000            8.000000
max         9.000000           10.000000

📝 CATEGORICAL SUMMARY
         department survey_date  \
count            30          30
unique            6          30
top     Engineering  2026-01-15
freq              6           1

                                            response_text
count                                                  30
unique                                                 30
top     Great team environment but limited growth oppo...
freq                                                    1

================================================================================
✓ Inspection Complete
================================================================================

---

## Practice Exercise

Now it's your turn! Complete the following tasks:

In [ ]:
# EXERCISE 1: Preview the data
# TODO: Display the first 8 rows using head()

# Your code here:

In [ ]:
# EXERCISE 2: Check the structure
# TODO: Use info() to check data types and missing values

# Your code here:

In [ ]:
# EXERCISE 3: Get statistical summary
# TODO: Use describe() to get statistics for numeric columns

# Your code here:

In [ ]:
# EXERCISE 4: Answer these questions based on your inspection
# (Write your answers as comments)

# Q1: How many rows and columns are in the dataset?
# Answer: 

# Q2: Are there any missing values? If yes, in which columns?
# Answer: 

# Q3: What is the average satisfaction_score?
# Answer: 

# Q4: What is the most common department?
# Answer: 

# Q5: What data type is the 'survey_date' column?
# Answer:

---

## Key Takeaways

### ✅ Always Inspect Before Analysis

1. **head()** - Quick visual preview
   - See column names and sample values
   - Check data alignment
   - Default shows 5 rows

2. **info()** - Structural health check (MOST IMPORTANT)
   - Reveals data types
   - Shows missing values (non-null counts)
   - Displays memory usage

3. **describe()** - Statistical summary
   - Mean, median, std, min, max
   - Percentiles for understanding distribution
   - Helps spot outliers

### 🎯 Best Practices

- **Always run all three methods** when first loading data
- **Check for missing values** using info() and isnull()
- **Verify data types** match expectations
- **Look for outliers** in describe() output
- **Understand your data** before making any transformations

### ⚠️ Common Mistakes to Avoid

- Starting analysis without inspection
- Assuming data types are correct
- Missing hidden null values
- Not checking for outliers
- Relying only on head() for understanding data

---

## Next Steps

Now that you can inspect DataFrames:
1. Practice on different datasets
2. Learn data cleaning techniques
3. Master data type conversions
4. Handle missing values properly

**Remember: Inspection is a foundational Data Science habit!**

---

## Additional Resources

- [Pandas head() Documentation](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.head.html)
- [Pandas info() Documentation](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.info.html)
- [Pandas describe() Documentation](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.describe.html)
- [Data Inspection Best Practices](https://pandas.pydata.org/docs/user_guide/basics.html)